# Generated by Django 4.0.1 on 2022-02-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='donation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
